[package]
name = "ptycore"
version = "0.1.0"
edition = "2021"

[dependencies]
portable-pty = "0.9.0"
anyhow = "1"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.27", features = ["process", "signal"] }
