[package]
name = "ptyd"
version = "0.1.0"
edition = "2021"

[dependencies]
portable-pty = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.21"
anyhow = "1"
which = "4"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.27", features = ["signal", "process"] }
